language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

cache:
  directories:
  - "$HOME/.composer"

before_install:
  - composer validate
  
install:
  - composer install --no-interaction -o --prefer-dist --no-suggest
  
before_script:
  - mkdir -p build/logs

script:
  - php -l src/
  - composer check-syntax
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
   - php vendor/bin/php-coveralls -v
